.github/workflows/nightly.yml

This pipeline runs nightly. It updates the recipe to build the latest commit from "main" in the TileDB-SOMA repo, and force pushes to the branch "nightly-build", which triggers the feedstock builds on Azure. Because `upload_on_branch: main` is set in `conda-forge.yml`, any binaries produced by this nightly test build are never uploaded to anaconda.org
Other details:
* "-nightly" is appended to the version string. This makes it easier to read the logs, and also ensures that the Python client always builds against the locally built libtiledbsoma
* The pipeline runs every night, but can also be manually triggered in the Actions UI or by editing the workflow file
You can see how this works on my fork:
* [nightly-build branch](https://github.com/jdblischak/tiledbsoma-feedstock/tree/nightly-buil …

Add GitHub Actions pipeline that triggers a nightly feedstock build

---

.github/workflows/nightly.yml

Followup to PR #12. Embarrassingly I must have somehow got lost in the various Azure builds, and didn't notice that I used an invalid version string for conda recipes. This PR updates the version string for the nightly builds to satisfy both conda and setuptools requirements:
* [conda](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=recipe%20meta.yaml#package-version): cannot include dashes
* setuptools: must adhere to [PEP 440](https://peps.python.org/pep-0440/)
I went with X.X.X.devYYYYMMDD, but I'm open to other options that satisfy the requirements. Note that X.X.X corresponds to the latest version in the conda recipe. It's possible to instead use the current version string in the upstream Git repo, but I'm trying to avoid prematurely …

Fix version string for nightly build

---

.github/scripts/nightly/add-and-commit.sh
.github/scripts/nightly/update-feedstock.sh
.github/scripts/nightly/update-recipe.sh
.github/workflows/nightly.yml

This updates the existing nightly builds to upload the conda binaries that are created. It labels the binaries with the tag "nightlies" so that normal end users are not affected. Developers can install the nightly conda binaries by specyfing the channel `-c "tiledb/label/nightlies"` when installing with conda.
You can see the example commits it creates on my fork:
* [nightly-build branch](https://github.com/jdblischak/tiledbsoma-feedstock/tree/nightly-build)
* [example commit that updates recipe and feedstock files](https://github.com/jdblischak/tiledbsoma-feedstock/commit/85610d37f9afe2840216be2c3525b9a96ca7c83d)
* [example commit that rerenders feedstock](https://github.com/jdblischak/tiledbsoma-feedstock/commit/22b4e8011be6505e5b416fc909a5ed56268178cf) - note that it changes the upload …

Rerender and upload nightly binaries

---

recipe/meta.yaml

#24 gets us TileDB-SOMA 1.2.4: https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.2.4
Latest tagged in GitHub, and in [PyPI](https://pypi.org/project/tiledbsoma/#history), is 1.2.5: https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.2.5
So this PR will get PyPI and Conda deliverables both on latest-released
The only dependency update here is `somacore` 1.0.2 -> 1.0.3 but that's handled by
https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/main/recipe/meta.yaml#L103
Tracking: https://github.com/single-cell-data/TileDB-SOMA/issues/1455

TileDB-SOMA 1.2.5

---

README.md
recipe/meta.yaml

In PR #24, I removed the top-level about section in favor of separate about sections per output. This added some redundancy (which we could probably solve with some YAML/jinja2 hacking if we really wanted to), but had the big benefit of having accurate summary and description sections on anaconda.org.
While the top-level about section isn't required for conda, it is required by `conda smithy rerender` to populate the README. This is why the [nightly builds are currently failing](https://github.com/TileDB-Inc/tiledbsoma-feedstock/actions/workflows/nightly.yml), eg [build #58 from 2 days ago](https://github.com/TileDB-Inc/tiledbsoma-feedstock/actions/runs/5195173018/jobs/9367627772).
Note that the README rendering for a recipe with multiple outputs is rather unfortunate. There is no newline …

Add back top-level about section (required for rerendering)

---

recipe/meta.yaml

We use features from recent versions of attrs, but did not specify that we needed this version. In an environment that, for whatever reason, had an earlier version installed, this would cause importing tiledbsoma to fail.

Fully specify attrs dependency.

---

recipe/meta.yaml

Following our currently established procedure at
As always (please see the above wiki) this isn't to _be_ released but rather to check the _feasibility_ of tagging a release.
Food for thought: The four PRs at the tip of https://github.com/single-cell-data/TileDB-SOMA/commits/release-1.2 as of today are all app-level -- and as such shouldn't affect package pins -- _except_ for https://github.com/single-cell-data/TileDB-SOMA/pull/1484/files. That PR affects the `numba` pin, only for Python 3.11: from 0.57.0rc1 to 0.57.0. However, in this repo's `recipe/meta.yaml` we have no `numba` constraints so I don't understand what we do or do not need to do new here.
Another note: I haven't re-renedered yet but I will attempt …

TileDB-SOMA 1.2.6 pre-release check

---

recipe/meta.yaml

Following
and with pre-release green-light check from #30

TileDB-SOMA 1.2.7

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Following our release procedure at https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases, as #34 passed Conda pre-check and https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.3.0 has been tagged

tiledbsoma 1.3.0

---

recipe/meta.yaml

TileDB-SOMA doesn't require a particular version of pyarrow because it does not link against any libarrow library directly.
x-ref: https://github.com/TileDB-Inc/tiledb-vcf-feedstock/pull/91

Loosen pyarrow pinning

---

.github/workflows/nightly.yml

mamba-org/provision-with-micromamba is deprecated (https://github.com/mamba-org/provision-with-micromamba/pull/122)

Migrate to mamba-org/setup-micromamba@v1

---

recipe/build-libtiledbsoma.sh
recipe/build-tiledbsoma-py.sh

This ensures in a multi-package build scenario each source build starts with a clean directory.
This is a further of the initial work that cleaned up the R package after each build.
Note: I didn't bump the build number because this won't cause any artifact changes and we don't need to re-upload.

Always clean up Python and C++ builds

---

.github/workflows/nightly.yml

conda-smithy checks if it is the latest version available, and since the job caches the conda env, it fails to rerender the feedstock every time there is a new conda-smithy release

Always update conda-smithy for nightly job

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

After #55 and #56
Standard release procedure: https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
See also https://github.com/single-cell-data/TileDB-SOMA/issues/1862

tiledbsoma 1.5.0

---

recipe/meta.yaml

tiledbsoma 1.6.1

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
conda-forge.yml
recipe/meta.yaml

Following our established procedure at
with the exception that TileDB-SOMA latest is 1.6.1 (see also #68) so here we are going to merge to the `release-1.5` branch of this repo, on the advice of @ihnorton. See also #69 for the pre-check PR.

tiledbsoma 1.5.2

---

.gitignore
recipe/meta.yaml

See also #70 for a previous PR on this branch (for 1.5.2). See #72 for the pre-check PR.

tiledbsoma 1.5.3

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
build-locally.py
recipe/meta.yaml

This is on `main` with tiledbsoma 1.7.2. See also #91 which attempts a pre-check for 1.8.0.
This doesn't bump any application-level versions -- hence build number 1. This works around problems that have recently arisen in our dependencies, problems which made a previously solvable recipe no longer solvable.
Solver issue:
```
744:    Encountered problems while solving:
745-      - package tiledb-2.19.1-hc0b898c_0 requires libcurl >=7.87.0,<8.0a0, but none of the providers can be installed
746-
747-    Could not solve for environment specs
748-    The following packages are incompatible
749-    ├─ libgoogle-cloud-storage 2.21.*  is installable and it requires
750-    │  └─ libgoogle-cloud [2.21.0 h31df0ca_0|2.21.0 h31df0ca_1|2.21.0 h72bcb37_2], which requires
751-    │     └─ libcurl …
```

Rerender, and fix `libgoogle-cloud` issues

---

recipe/meta.yaml

We have some cloud CI failing because:
* `tiledbsoma-feedstock` has `somacore >= 1.0.7` https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/6663e5111ccd0a74dd5e4f01781918f4bf52879d/recipe/meta.yaml#L112
* https://github.com/single-cell-data/TileDB-SOMA/pull/2001 is a PR that needs `somacore` 1.0.8` -- there are fails without that PR and with 1.0.8, and fails with that PR and without 1.0.8
* The aforementioned cloud PR is just a patch on top of existing `tiledbsoma` 1.7
* So I need to update `tiledbsoma-feedstock` to pin to `somacore == 1.0.7` -- this PR

Use `somacore == 1.0.7` for `tiledbsoma` 1.7.2

---

recipe/meta.yaml

A previous version of tiledb-soma erroneously marked itself as compatible with versions of tilebsoma v1.0.8. This is because the PyPI package (https://github.com/single-cell-data/TileDB-SOMA/blob/1.8.0/apis/python/setup.py#L332) lists itself as only compatible with == a version, but this Conda package listed itself as compatible with >= a version.

Make `somacore` dependency exact to match `tiledbsoma`

---

.github/scripts/nightly/check-azure-status.sh
.github/workflows/nightly-azure-status.yml
.github/workflows/nightly.yml

This PR updates the nightly builds so that they open an Issue if they fail.
I created 3 new [labels](https://github.com/TileDB-Inc/tiledbsoma-feedstock/labels) (which is how my `open-issue` action knows whether to open a new issue or comment on an existing open one)
Now an Issue will be opened for any of the following failures:
* The nightly Azure build failed (the most important). These Issues will be labeled `nightly-failure`
* The GitHub Actions workflow to trigger the nightly build failed. These Issues will be labeled `nightly-setup-failure`. These failures are almost always spurious and can usually be fixed with a restart
* The GitHub Actions workflow to check the Azure nightly status failed. These Issues will be labeled `nightly-azure-status-failure`. These errors should be rare
I …

[ci skip] Open Issue if nightly Azure build fails

---

.github/workflows/nightly.yml

Have to pin to 3.31.1 until the Issue with 3.32.0 is resolved. It rejects the Azure project information in `conda-forge.yml`
Bug report filed at https://github.com/conda-forge/conda-smithy/issues/1864
https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/a05739d3e236bb355b2c772c3c5ac0ebdf6ec414/conda-forge.yml#L11-L14
Successful [run](https://github.com/jdblischak/tiledbsoma-feedstock/actions/runs/8300733407) on my fork

[ci skip] Pin conda-smithy to 3.31.1

---

.github/workflows/nightly-azure-status.yml

We only need to check the Azure status of the nightly build (and potentially open an Issue to report a failure) on the main feedstock repository. This is creating too much unnecessary noise on my fork.
xref: follow-up to #99

[ci skip] Do not open Issue for failed Azure nightly build on a fork

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_fmt10spdlog1.12.yaml
.ci_support/linux_64_fmt9spdlog1.11.yaml
.ci_support/osx_64_.yaml
README.md
recipe/conda_build_config.yaml

Closes #101
Supersedes #103 
This PR fixes the current conda solver errors that are failing the nightlies and blocking new PRs by separating the linux-64 build into two separate variants:
1. conda-forge: builds against tiledb from conda-forge and uses the latest conda-forge pins
2. TileDB Cloud: builds against the statically linked "for-cloud" tiledb binary from the tiledb channel and uses the outdated pins (fmt 9 and spdlog 1.11) required for installing into the cloud conda environments

Build two variants: one for cloud and one for conda-forge

---

.github/workflows/nightly.yml

Undoes PR #102. The problems with conda-smithy 3.32.0 were fixed in [3.33.0](https://github.com/conda-forge/conda-smithy/releases/tag/v3.33.0)
xref: https://github.com/conda-forge/conda-smithy/issues/1864, https://github.com/conda-forge/conda-smithy/pull/1871
Successful [run](https://github.com/jdblischak/tiledbsoma-feedstock/actions/runs/8442281103/job/23123352317) on my fork

[ci skip] Unpin conda-smithy for nightly builds

---

conda-forge.yml

We previously enabled flexible channel priority in order to install the py37 tiledb-py from the tiledb channel. Now that we've dropped Python 3.7, this should no longer be necessary.
No need to bump the build number. Just want to confirm the solver can handle this. Then we can merge, and it will be enforced for future builds.
Lastly I made a minor change to update the [deprecated `test_on_native_only` field](https://conda-forge.org/docs/maintainer/conda_forge_yml/#test-on-native-only).
Rerendering had no effect

Return to strict channel priority

---

recipe/build-r-tiledbsoma.sh

Per a request of @johnkerl a quick test that the `arrow` R package loads and runs.

Add a build-time litmus test for the `arrow` R package

---

recipe/meta.yaml

Needs https://github.com/TileDB-Inc/somacore-feedstock/pull/14

tiledbsoma 1.10.2

---

.github/workflows/automerge.yml

Closes #147 
The latest round of changes from `conda smithy rerender` edits `.github/workflows/automerge.yml`. GitHub requires the token to have the `workflows` permission in order to edit a workflow file, and our token only has the standard write permission.
This PR performs the rerendering that edits `.github/workflows/automerge.yml`. This will unblock the nightly setup job since it will no longer edit the workflow file.

Rerender to fix nightly setup job

---

recipe/meta.yaml

tiledbsoma 1.11.0

---

recipe/meta.yaml

Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases), except, no pre-check PR -- 1.11.0 was already a very recent check.
This is due solely to https://github.com/single-cell-data/TileDB-SOMA/issues/2556#issuecomment-2110422212

tiledbsoma 1.11.1

---

.github/scripts/nightly/update-recipe.sh
recipe/meta.yaml

* Perform unshallow clone for updated version.py
* Bump numpy upper bound for python 3.12 which uses 1.26
Unfortunately the nightly osx-* builds are still broken
xref: https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/153

Fix linux-64 nightly errors

---

recipe/meta.yaml

Release notes: https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.11.3

tiledbsoma 1.11.3

---

.ci_support/linux_64_fmt10spdlog1.13.yaml
.ci_support/linux_64_fmt9spdlog1.11.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

Followup to #174. In that PR, we set the lower bound `pyarrow >= 14`. However, we can't do this because TileDB Cloud still has pyarrow 11 installed.
This PR:
* Fixes the conda solver problem by removing the lower bound on pyarrow
* In addition it purposefully builds against pyarrow 11. This is a bit overkill since pyarrow doesn't use run exports. However, I wanted to be confident that it could solve an env with pyarrow 11. We could relax this part in the future
* Completely skip the Python 3.12 builds. We don't need them now, and it is too much trouble at the moment. Once we relax the above, we can probably add them back
* Stopped pyarrrow-hotfix from being installed in the non-cross-compiled build envs
* Migrated the recipe to use [`- {{ stdlib("c") …

Remove lower bound on pyarrow

---

recipe/meta.yaml

Followup to #176. I had removed `__osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}` from the Python requirements, but I forgot to remove it from the C++ and R requirements.
I didn't bump the build number. These lines don't hurt anything; they are just unnecessary clutter now that we've migrated to `{{ stdlib("c") }}`.
Rerendering had no effect.

Remove remaining uses of MACOSX_DEPLOYMENT_TARGET

---

recipe/meta.yaml

#202 contained a copy-paste from the pre-check PR #201 of the sha/hash info. I forgot to update to the released hash on 202. This PR fixes that.
I noticed this while testing https://github.com/TileDB-Inc/TileDB-REST-UDF-Docker-Images/pull/721 following our [established procedure](https://www.notion.so/785d165226074071872a8b797133d36c?v=c168da78516e487eac3746d38924fa97&p=d1c7a37761b04cf699a705bb8963dea9&pm=s) -- on-image I found
```
tiledbsoma.__version__              1.14.1.post3.dev12177573296
TileDB core version (libtiledbsoma) 2.26.1
python version                      3.9.19.final.0
OS version                          Linux 6.8.0-1016-aws
```
The `1.14.1.post3.dev12177573296` needs to be `1.14.2`.
https://github.com/single-cell-data/TileDB-SOMA/issues/3075 …

tiledbsoma 1.14.2 hash-fix

---

recipe/meta.yaml

Closes #208 
`otool` isn't available in the new macOS-13 image (for more details see https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/208#issuecomment-2414485496)
Successfully built on my fork in https://github.com/jdblischak/tiledbsoma-feedstock/commit/351bee218d82ba555685f5f3aa303864c1e975be
Not actually needed for osx-arm64 at the moment, but figured I'd rather be safe than sorry (in other words, no way to know if or when `otool` may disappear from a future arm64 image).
No need to bump build number. This only affects the test section, and is simply to fix the broken osx-64 nightly.

Install cctools in test section for `otool` in macOS-13 image

---

.github/scripts/nightly/update-recipe.sh

Closes #216
Syncing somacore version with upstream (https://github.com/single-cell-data/TileDB-SOMA/pull/3250)
xref: #211

Bump somacore to 1.0.22 for nightly feedstock builds

---

.github/scripts/nightly/update-recipe.sh

Closes #221 
Trying out the new conda-forge feedstock behavior to be able to skip CI jobs in a PR 🤞 
xref: https://github.com/single-cell-data/TileDB-SOMA/pull/3274

[ci skip] Bump somacore to 1.0.23 for nightly feedstock builds

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_.yaml
build-locally.py
recipe/meta.yaml

Closes #229
Companion to #238 

Update `py39cloud` variant to 1.15.0

---

recipe/meta.yaml

tiledbsoma 1.15.1

---

recipe/meta.yaml

tiledbsoma 1.15.2, `py39cloud` branch

---

.ci_support/linux_64_.yaml
.ci_support/migrations/spdlog114.yaml
.ci_support/migrations/spdlog115.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
recipe/meta.yaml

[sc-61669](https://app.shortcut.com/tiledb-inc/story/61669/tiledbsoma-1-15-3)

tiledbsoma 1.15.3

---

.github/scripts/nightly/cpp20.patch
.github/scripts/nightly/update-feedstock.sh
.github/scripts/nightly/update-recipe.sh

Closes #230
This applies the fixes from @XanthosXanthopoulos in #246 (with minor modifications by me) to the nightly build.
I used `[ci skip]` since updating the nightly workflow has no impact on the current feedstock builds.
I also removed the temporary code to update the somacore version. Currently both the recipe and the upstream `setup.py` specify somacore 1.0.26.
I ran the [nightly workflow on my fork](https://github.com/jdblischak/tiledbsoma-feedstock/actions/runs/12875784835) to confirm there were no obvious errors in the execution of the nightly setup workflow. I've also ran various tests on my fork implementing these changes. The nightly should pass, but if it does fail, it will open a new Issue.

[ci skip] Compile with C++20 to fix nightly builds

---

recipe/conda_build_config.yaml

Background:
* We use `conda_build_config.yaml` to restrict the cloud build to only a py39 variant
* conda-forge added a new global pin `is_python_min` to their [global pinning file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/5c1ec81641eaa369551d013939ddae864efe92d9/recipe/conda_build_config.yaml#L840), which is `# part of a zip_keys: python, python_impl, numpy, is_python_min`
* If we don't define all the zip keys, then our configuration is ignored, and thus `conda smithy rerender` tries to add all the Python variants supported by conda-forge
* This is what caused the problem yesterday in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/256
* I first learned about this problem 2 weeks ago when it broke our nightly tiledb-py-feedstock builds (where we also …

Add new conda-forge key `is_python_min` to fix rerendering

---

recipe/meta.yaml

https://github.com/single-cell-data/TileDB-SOMA/issues/3629

tiledbsoma 1.15.5, `py39cloud`

---

recipe/meta.yaml

https://github.com/single-cell-data/TileDB-SOMA/issues/3662

tiledbsoma 1.15.6, `py39cloud` branch

---

recipe/meta.yaml

https://github.com/single-cell-data/TileDB-SOMA/issues/3662
[[sc-62929]](https://app.shortcut.com/tiledb-inc/story/62929/tiledbsoma-1-15-7)

tiledbsoma 1.15.7, `py39cloud` branch

---

.gitignore
recipe/conda_build_config.yaml

Closes #277
xref: https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/277#issuecomment-2666360359

Limit to R 4.3 until TileDB-SOMA-R is tested with R 4.4 on macOS

---

.github/scripts/nightly/update-recipe.sh

Closes #285 
xref: #217, https://github.com/single-cell-data/TileDB-SOMA/pull/3756

Bump somacore to 1.0.28 for nightly feedstock builds

---

.ci_support/linux_64_.yaml
.gitignore

**summary:** We need r-tiledbsoma 1.15.7 built for R 4.4 to migrate the cloud notebook image to R 4.4
**details:**
* A customer has requested that we migrate the cloud R notebook image from 4.3 to 4.4, but the migration effort is currently blocked by conda solver errors (https://github.com/TileDB-Inc/TileDB-Cloud-JupyterHub/pull/824)
* Because conda-forge has started building its packages for R 4.4, adding support for R 4.4 in this feedstock required only a simple rerender (for more explanation see https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/284#discussion_r1983621378)
* I didn't bump the build number. We only want to update the new linux-64 conda binary for r-tiledbsoma built with R 4.4
* We are currently troubleshooting problems with the new R 4.4 builds on osx-64 and …

Build r-tiledbsoma 1.15.7 with R 4.4 for cloud deployment only

---

recipe/build-libtiledbsoma.sh
recipe/build-r-tiledbsoma.sh
recipe/build-tiledbsoma-py.sh
recipe/cc_wrap.sh
recipe/cxx_wrap.sh
recipe/meta.yaml

https://github.com/single-cell-data/TileDB-SOMA/issues/3720 [[sc-63626]](https://app.shortcut.com/tiledb-inc/story/63626/tiledb-soma-1-16-0)
SIbling: #288

tiledbsoma 1.16.0, `py39cloud` branch

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
recipe/conda_build_config.yaml
recipe/meta.yaml

The R 4.4 r-tiledbsoma build was already passing on linux-64, and the fix for the osx-64 looked straightforward.
Followup to #278. For more details see #279

Add R 4.4 builds for linux-64 and osx-64

---

recipe/meta.yaml

tiledbsoma 1.16.1, `main` branch

---

recipe/meta.yaml

This is a quality-of-life improvement to catch any potential problems with the R package well before on image testing. This can wait until we finish the more urgent 1.16.1 deployment.
I followed the official conda-forge guidance for [Running `testthat` tests](https://conda-forge.org/docs/maintainer/adding_pkgs/#running-testthat-tests). By installing all the optional dependencies except the big data packages (which I don't want to package for conda) and the bioconductor packages (I don't want to get the bioconda channel involved), we run the majority of the tests. And it only takes a little over 3 minutes, so for two R variants this only adds another 6-7 minutes to an already long build. Seems worth it to me.
```
══ Results ═══════════════════════════════════════════════════════════════════ …
```

Run R package tests

---

.github/scripts/nightly/update-recipe.sh

Closes #302 
In the next update PR, `more-itertools` needs to be added as a run requirement, and this temporary code can be removed.

[ci skip] Install new Python requirement more-itertools in nightly build

---

.github/scripts/nightly/update-recipe.sh
recipe/meta.yaml

Closes #309 
This PR does two things to update the nightly build:
* It restores the standard 2 space indentation of the source section of the recipe. Our nightly build is mostly a series of `sed` commands, so the exact spacing is required. The reason the nightly setup build started failing on Friday is because the 1.16.2 update PR used a single space for indentation (#309) 
* Removed the temporary code to add the new dependency `more-itertools`, since that was added in 1.16.2
There is no point in running the Azure builds for this PR, hence the `[ci skip]`. I confirmed this will fix the nightly setup job via a [manual run on my fork](https://github.com/jdblischak/tiledbsoma-feedstock/actions/runs/14840820457).

[ci skip] Update nightly build post-1.16.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.scripts/create_conda_build_artifacts.sh
conda-forge.yml

I configured [`conda-forge.yml`](https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure) to [upload the built conda binaries as Azure pipeline artifacts](https://conda.discourse.group/t/are-built-packages-saved-as-artifacts-when-a-pr-is-tested/934/2). Here are example artifacts from a run on my [fork](https://dev.azure.com/jdblischak/feedstock-builds/_build/results?buildId=1251&view=artifacts&pathAsName=false&type=publishedArtifacts).
This should help with future troubleshooting, because the whole `build_artifacts/` directory is uploaded even if the build fails at some step (`condition: succeededOrFailed()`).
The only unknown for me is how long these artifacts are stored. It's almost 30 MB of artifacts per run, which will add up. Hopefully they are auto-deleted similar to the …

Store the conda build_artifacts dir as an Azure pipeline artifact

---

.github/scripts/nightly/update-recipe.sh

Closes #316 
The main branch of TileDB-SOMA targets tiledb 2.28. R enforces its minimum required version, so the builds are failing. This PR updates the nightly feedstock build to use the tiledb 2.28 stack. Once 1.17.0 is merged, this temporary code can be deleted.
As a test on my fork, I am running last night's setup with the 2.28 requirements (https://github.com/jdblischak/tiledbsoma-feedstock/commit/4d41578880d4ddaba90b7c7c4c4de94ca4b114f5)

[ci skip] Bump nightly build to use 2.28 stack

---

recipe/meta.yaml

Update TileDB-SOMA to release 1.17.0.

TileDB-SOMA 1.17.0, `py39cloud` branch

---

recipe/meta.yaml

Update TileDB-SOMA to release 1.17.0.

TileDB-SOMA 1.17.0, `main` branch

---

.github/scripts/nightly/update-recipe.sh

Undo #317 now that 1.17.0 was merged in #314

[ci skip] Remove temporary nightly patch to install 2.28 stack
