recipe/meta.yaml
x-ref https://github.com/single-cell-data/TileDB-SOMA/issues/1436
=> Require typing-extensions >= 4.1

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml
Following
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/36
* https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
=> tiledbsoma 1.4.0

recipe/meta.yaml
Following on https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/42
=> tiledbsoma 1.4.2

recipe/meta.yaml
Following our established procedure
=> tiledbsoma release 1.4.3

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
Following https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
=> tiledbsoma 1.5.0rc1

recipe/meta.yaml
=> tiledbsoma 1.5.0rc2

recipe/meta.yaml
I am starting this rolling in case of any delay with 1.5.0 -- if 1.5.0 comes out soon I'll cancel this
Established procedure:
=> tiledbsoma 1.5.0rc3

.ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, recipe/conda_build_config.yaml
Follows on #57 while undoing part of #46 -- which I should have done on #57
=> Publish tiledbsoma 1.5.0 to `main` channel

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
Standard release procedure: https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
See also #61 for a recent pre-check, in particular https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/61#issuecomment-1816471120
=> tiledbsoma 1.5.1

.gitignore, recipe/meta.yaml
Following our established procedure:
Pre-check PR: #74
=> tiledbsoma 1.6.2

.ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
Incorporates lessons/findings from:
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/77
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/78
* https://github.com/TileDB-Inc/somacore-feedstock/pull/10
* https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/79
* https://github.com/TileDB-Inc/TileDB-Cloud-JupyterHub/pull/604
* https://github.com/TileDB-Inc/TileDB-REST-UDF-Docker-Images/pull/534
=> tiledbsoma 1.7.0

.ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, recipe/meta.yaml
=> tiledbsoma 1.7.1

recipe/meta.yaml
=> tiledbsoma 1.7.2

.ci_support/osx_64_.yaml, recipe/build-r-tiledbsoma.sh, recipe/build-tiledbsoma-py.sh, recipe/cc_wrap.sh, recipe/conda_build_config.yaml, recipe/cxx_wrap.sh, recipe/meta.yaml
=> tiledbsoma 1.8.0

recipe/meta.yaml
=> tiledbsoma 1.8.1

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_fmt10spdlog1.12.yaml, .ci_support/linux_64_fmt9spdlog1.11.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/2311
[sc-43673]
=> tiledbsoma 1.9.1

recipe/meta.yaml
=> tiledbsoma 1.9.2

recipe/meta.yaml
=> tiledbsoma 1.9.3

recipe/meta.yaml
=> tiledbsoma 1.9.4

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/2414
[sc-44854]
=> tiledbsoma 1.9.5

recipe/meta.yaml
=> tiledbsoma 1.10.0

recipe/meta.yaml
Following our [established procedure](https://www.notion.so/785d165226074071872a8b797133d36c?v=c168da78516e487eac3746d38924fa97&p=d1c7a37761b04cf699a705bb8963dea9&pm=s)
=> tiledbsoma 1.10.1

recipe/meta.yaml
=> tiledbsoma 1.11.4

.ci_support/linux_64_fmt10spdlog1.13.yaml, .ci_support/linux_64_fmt9spdlog1.11.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, recipe/meta.yaml
=> tiledbsoma 1.12.1

recipe/meta.yaml
=> tiledbsoma 1.12.3

recipe/meta.yaml
[[sc-53053]](https://app.shortcut.com/tiledb-inc/story/53053/tiledb-soma-1-13-1)
=> tiledbsoma 1.13.1

recipe/meta.yaml
=> tiledbsoma 1.15.0rc3

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, .scripts/run_osx_build.sh, build-locally.py, recipe/meta.yaml
=> tiledbsoma 1.15.0

recipe/meta.yaml
=> tiledbsoma 1.15.2

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/3618
Sibling: #258
=> tiledbsoma 1.15.4, `main` branch

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/3618
Sibling: #257
=> tiledbsoma 1.15.4, `py39cloud` branch

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/3629
=> tiledbsoma 1.15.5, `main`

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/3662
=> tiledbsoma 1.15.6, `main` branch

recipe/meta.yaml
https://github.com/single-cell-data/TileDB-SOMA/issues/3662
[[sc-62929]](https://app.shortcut.com/tiledb-inc/story/62929/tiledbsoma-1-15-7)
=> tiledbsoma 1.15.7, `main` branch

.ci_support/osx_64_.yaml, .scripts/run_docker_build.sh, build-locally.py, recipe/build-libtiledbsoma.sh, recipe/build-r-tiledbsoma.sh, recipe/build-tiledbsoma-py.sh, recipe/cc_wrap.sh, recipe/conda_build_config.yaml, recipe/cxx_wrap.sh, recipe/meta.yaml
Add release 1.16.2 to the conda feedstock
=> tiledbsoma 1.16.2, `main` branch

.github/CODEOWNERS, README.md, recipe/meta.yaml
How I created this PR:
* Manually updated list in `recipe/meta.yaml`
* Ran `conda smithy rerender`
* Committed everything together with `[ci skip]`
=> [ci skip] Update maintainers

.azure-pipelines/azure-pipelines-linux.yml, .scripts/create_conda_build_artifacts.sh, conda-forge.yml
=> [py39cloud] Store the conda build_artifacts dir as an Azure pipeline artifact

.azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_.yaml, .ci_support/osx_64_.yaml, .ci_support/osx_arm64_.yaml, README.md, recipe/meta.yaml
Update conda with the TileDB-SOMA 2.0.0 release
=> TileDB-SOMA 2.0.0
